### ISSUE TITLE
Add support for python 3

### ISSUE THREAD

**Issue by josuebrunel** [josuebrunel/pysxm#2]

**Comment by kounkou** [comment]
Tested with python `Python 3.5.2`, how will you guaranty portability with python versions >= 3 ?

**Comment by josuebrunel** [comment]
> Tested with python Python 3.5.2, how will you guaranty portability with python versions >= 3 ?

By continoues integration unless i got your question wrong.

**Comment by kounkou** [comment]
That's fine.
