### ISSUE TITLE
Serializing attributes with # in them

### ISSUE THREAD

**Issue by t4thfavor** [josuebrunel/pysxm#22]
I have objects that are created by type at runtime. They may or may not contain the "#" character.

When they do, I get an "Illegal Tag name Some#Field" error.  

Should these be valid in XML since they are not on the list of illegal characters (that I can find)? If so, then it should be easy to implement. 

I may be ill informed though, and in the event that # is illegal in a tag name in XML, the character should be escaped by the pysxm module if possible.

Example:
```python
import types
from pysxm.ext import DataComplexType
args={"DOCKET#NUMBER": "123456",
    "CASETYPE": "CSP0100001",
    "FILINGTYPE":"FLP0100001"}
obj = type("test",(DataComplexType, ), {})(**args)
print(type(obj))
print(obj)
```

**Comment by josuebrunel** [comment]
Hi @t4thfavor ,
I think *#* is not a valid character in an xml tag name https://stackoverflow.com/a/8066549/975774

**Comment by t4thfavor** [comment]
I've worked around this in my code. I think I have a unique enough case where this should not be a problem for anyone using these libraries in a more conventional manner.

**Comment by t4thfavor** [comment]
I meant to close the issue :)
