### ISSUE TITLE
Having all the module inside __init__ is weird

### ISSUE THREAD

**Issue by kounkou** [josuebrunel/pysxm#6]
Having the all module pysxm within the __init__ is weird. 
Indeed, people will fail to understand what's the architecture of pysxm from looking into the project tree.
__init__ shall be empty in our case and let's create a pysxm.py inside the pysxm dir, rooted with a __init__.py as well. Sounds good ?

**Comment by josuebrunel** [comment]
Go on

**Comment by kounkou** [comment]
Changing the state of this issue if you don't see any drawback ? @josuebrunel
